

services:
  vite-app:
    build: .
    restart: always
    container_name: test-project
    volumes:
      - .:/app
      - /app/node_modules
    ports:
      - "3037:5173"
    environment:
      - CHOKIDAR_USEPOLLING=true # Nécessaire pour que Vite détecte les changements
    stdin_open: true
    tty: true


# services:
#   mairie:
#     build: .
#     container_name: admin-front-front
#     restart: always
#     ports:
#       - "3003:80"
#     networks:
#       - angara
#     volumes:
#       - .:/app
#       - ./nginx.conf:/etc/nginx/conf.d/default.conf

# networks:
#   angara:
#     external: true

