

# services:
#   vite-app:
#     build: .
#     restart: always
#     container_name: test-project
#     volumes:
#       - .:/app
#       - /app/node_modules
#     ports:
#       - "3037:5173"
#     environment:
#       - CHOKIDAR_USEPOLLING=true # Nécessaire pour que Vite détecte les changements
#     stdin_open: true
#     tty: true


services:
  app:
    build: .
    container_name: test-project
    restart: always
    ports:
      - "3037:80"
    volumes:
      - .:/app
      - ./nginx.conf:/etc/nginx/conf.d/default.conf


